services:
  ros:
    container_name: ros
    build:
      context: .
    environment:
      - DISPLAY=novnc:0.0
    networks:
      - rosnet
    volumes:
      - rosvol:/root/robotics/
      - nvim_cache:/root/.local/share/nvim/
  novnc:
    container_name: novnc
    image: theasp/novnc
    environment:
      - DISPLAY_WIDTH=1512
      - DISPLAY_HEIGHT=982
      - RUN_XTERM=no
    ports:
      - "8080:8080"
    networks:
      - rosnet
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

networks:
  rosnet:
    driver: bridge

volumes:
  rosvol:
  nvim_cache:
